compute_fairness_metrics: true
data:
  client_split: 0.2
  dataset:
    name: adult
    path: ./data
  distribution:
    beta: 1.0
    name: dir
  keep_test: true
  sampling_perc: 1.0
  server_split: 0.0
  server_test: true
  uniform_test: false
eval:
  eval_every: 1
  locals: true
  post_fit: true
  pre_fit: true
  server: true
  task: classification
exp:
  device: cpu
  seed: 42
logger:
  log_dir: /storage/fl-lab/runs/run_3
  name: CsvLog
protocol:
  eligible_perc: 1.0
  n_clients: 4
  n_rounds: 20
